name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky26a
        with:
          pdk: sky130A

      - name: Upload GDS/LEF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gds_output
          path: |
            runs/wokwi/*/gds/*.gds
            runs/wokwi/*/lef/*.lef

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky26a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky26a

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky26a

  submit:
    needs: [gds, precheck, gl_test, viewer]
    runs-on: ubuntu-24.04
    steps:
      - name: Download GDS/LEF from gds job
        uses: actions/download-artifact@v4
        with:
          name: gds_output
          path: ./artifacts

      - name: Upload Tiny Tapeout submission artifact
        uses: actions/upload-artifact@v4
        with:
          name: tt_submission
          path: |
            ./artifacts/*.gds
            ./artifacts/*.lef
            src/project.v
